# Change these first
owner: UniSynTechnologies
repo: Upptime

sites:
  - name: UniSyn Webhost1
    check: "tcp-ping"
    url: 130.211.189.207
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: UniSyn Webhost2
    check: "tcp-ping"
    url: 104.197.180.165
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: UniSyn Webhost3
    check: "tcp-ping"
    url: 107.178.218.143
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: UniSyn Webhost4
    check: "tcp-ping"
    url: 23.236.52.200
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: UniSyn Webhost5
    check: "tcp-ping"
    url: 35.193.191.247
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: UniSyn Webhost6
    check: "tcp-ping"
    url: 34.123.58.9
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: UniSyn Webhost7
    check: "tcp-ping"
    url: 35.226.17.76
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: UniSyn Webhost8
    check: "tcp-ping"
    url: 35.223.22.129
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: UniSyn Webhost9
    check: "tcp-ping"
    url: 34.135.6.209
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: UniSyn Webhost10
    check: "tcp-ping"
    url: 34.170.116.178
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: UniSyn Open Hosting 1
    check: "tcp-ping"
    url: 34.16.44.80
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: UniSyn Open Hosting 2
    check: "tcp-ping"
    url: 104.197.128.162
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: UniSyn Open Hosting 3
    check: "tcp-ping"
    url: 104.197.146.59
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: UniSyn Webhost Budget 1
    check: "tcp-ping"
    url: 35.209.225.177
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: UniSyn Worker1
    check: "tcp-ping"
    url: 35.188.154.239
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: Butter Book Production
    check: "tcp-ping"
    url: 34.72.50.113
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png
  - name: UniSyn Pcare
    check: "tcp-ping"
    url: 104.197.204.95
    port: 443
    icon: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/03/15155324/cropped-unisyn-logo-orange-180x180.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.unisyn.tech
  # baseUrl: /Upptime
  logoUrl: https://unisyn-wp-assets.s3.amazonaws.com/unisyn-homepage/2021/05/14113831/unisyn-logo-sm.png
  name: UniSyn Technologies
  introTitle: "**UniSyn** is a local web design and development team, specializing in high quality websites and applications!"
  introMessage: This is our status page, here we (and you) can monitor the status of our sites, services, and applications to see just how dedicated we are to high availability in our hosting. 
  navbar:
    - title: UniSyn
      href: https://www.unisyn.tech
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
